---
- name: Ensure required packages are installed
  yum: pkg={{ item }} state=present
  with_items:
    - python-virtualenv
    - supervisor

- name: Add user beaver
  user: >
    name=beaver
    createhome=no
    group=adm
    home=/usr/share/beaver
    shell=/usr/sbin/nologin
    state=present
    system=yes

- name: Upgrade pip
  pip: name=pip extra_args=-U virtualenv=/usr/share/beaver state=present

- name: Install beaver
  pip: name=beaver virtualenv=/usr/share/beaver state=present

- name: Install required library by beaver
  pip: name=argparse virtualenv=/usr/share/beaver state=present

- name: Install beaver config
  template: >
    src=beaver.conf.j2
    dest=/etc/beaver.conf
    owner=root
    group=adm
    mode=0640
  notify: reload supervisorctl

- name: Create /etc/beaver.d
  file: path=/etc/beaver.d owner=root group=adm mode=0770 state=directory

- name: Install supervisor config
  copy: src=supervisor.conf dest=/etc/supervisord.conf
  notify: reload supervisorctl

- name: Ensure supervisor is running
  service: name=supervisord state=started
